#!/usr/bin/env python
from traitlets.config.loader import Config
try:
    get_ipython
except NameError:
    nested = 0
    cfg = Config()
else:
    cfg = Config()
    nested = 1


from IPython.terminal.embed import InteractiveShellEmbed
shell = InteractiveShellEmbed(config=cfg,
                              banner1="Fetch Interactive Shell 0.1.0",
                              exit_msg="Leaving Fetch Interactive Shell")

LOGO = r"""
    __________________________  __
   / ____/ ____/_  __/ ____/ / / /
  / /_  / __/   / / / /   / /_/ / 
 / __/ / /___  / / / /___/ __  /  
/_/   /_____/ /_/  \____/_/ /_/   
"""

import rospy
import fetch_api
from fetch_api import Arm, Base, Gripper, Head, Torso, ArmJoints
rospy.init_node("ifetch", anonymous=True)

arm = Arm()
base = Base()
gripper = Gripper()
head = Head()
torso = Torso()

shell(LOGO)
